app_login:
  path: /login
  controller: App\Controller\SecurityController::login

app_logout:
  path: /logout
  controller: App\Controller\SecurityController::logout

password:
  path: /compte_validate/{token}
  controller: App\Controller\SecurityController::changerMotDePasseToken