utilisateur:
    path: /
    controller: App\Controller\UtilisateurController::index

utilisateur_liste:
    path: /liste
    controller: App\Controller\UtilisateurController::index

utilisateur_creer:
    path: /creer
    controller: App\Controller\UtilisateurController::creer