security:
    resource: 'routes/security.yaml'

configuration:
    resource: 'routes/configuration.yaml'
    prefix: /configuration

utilisateur:
    resource: 'routes/utilisateur.yaml'
    prefix: /utilisateur

index:
    path: /index
    controller: App\Controller\CompliceController::index
